### ISSUE TITLE
Trouble with fresh nodered v.0.13.1

### ISSUE THREAD

**Issue by aborovsky** [mapero/node-red-contrib-mosca#3]
3 Feb 14:41:41 - TypeError: Cannot read property 'getNode' of undefined
   at Object.getNode [as get](node-rednode_modulesbeetoo-controllerredruntimenodesflowsindex.js:132:50)
   at MoscaInNode.Node.send (node-red\node_modules\beetoo-controller\red\runtime\nodes\Node.js:123:26)
   at EventEmitter.<anonymous> (node-red\node_modules\node-red-contrib-mosca\mosca.js:90:14)
   at emitTwo (events.js:92:20)
   at EventEmitter.emit (events.js:172:7)
   at Immediate._onImmediate (node-red\node_modules\mosca\lib\client.js:297:21)
   at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by martin-doyle** [comment]
Did you check my fork https://github.com/martin-doyle/node-red-contrib-mosca? Let me know if this works for you.
